AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  env:
    Type: String
  snsPrefix:
    Type: String

Resources:
  YelpVenueSyncTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Yelp Venue Sync Topic
      TopicName: !Sub ${snsPrefix}-${env}-yelp-venue-sync

Outputs:
  YelpVenueSyncTopicArn:
    Value: !Ref YelpVenueSyncTopic
